version: "3.5"

services:
  database:
    image: postres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postres
      POSTGRES_PASSWORD: postres
      POSTGRES_DB: postres

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    environment:
      PGADMIN_DEFAULT_EMAIL: postres@mail.ru
      PGADMIN_DEFAULT_PASSWORD: postres
      PGADMIN_CONFIG_SERVER_MODE: "False"
